### ISSUE TITLE
add support for Bandcamp

### ISSUE THREAD

**Issue by monban** [tgwizard/sls#115]
I'd like to add support for the Bandcamp app. I have scrubbed up the intents that it is using internally, but they never show up in the receiver. I'm rather new to Android development, perhaps I don't understand enough about how intents work.

I have created a branch at https://github.com/monban/sls/commit/50ebbdc4aa7dc457ab9daad9768eb7ab3de7cb4d maybe I'm doing something obviously wrong? Or is it impossible to receive another app's intents unless they are specifically trying to broadcast them? Thanks.

**Comment by HumbleBeeBumbleBee** [comment]
More people should contact bandcamp about this, and hopefully they will add support one day.
[support@bandcamp.com](mailto:support@bandcamp.com)
BandCamp is a great app and scrobbling is a nice tool to track listening habits.

**Comment by HumbleBeeBumbleBee** [comment]
>Thanks for the feedback, and for all your support. We don't have any current plans to integrate scrobbling, but I'll pass your suggestion and this forum on to our app gurus.
Well, that's more news than many app developers have given me.
Cheers to bandcamp.

**Comment by obama** [comment]
+1

**Comment by OseekerM** [comment]
Hi, any news about adding that app in to the scrobbler?

**Comment by jflory7** [comment]
I pinged the support email for Bandcamp and got this response, for what it's worth:

> Hey Justin,
>
> Thanks for the message! Last.fm support is something we're considering, but we don't have a set date on that just yet. Stay tuned as we continue to improve the app.

**Comment by OseekerM** [comment]
Hi Justin.

Thanks for the info..

With best regards,
Nariman Nazirov

21 марта 2017 г. 11:48 PM пользователь "Justin W. Flory" <
notifications@github.com> написал:

I pinged the support email for Bandcamp and got this response, for what
it's worth:

Hey Justin,

Thanks for the message! Last.fm support is something we're considering, but
we don't have a set date on that just yet. Stay tuned as we continue to
improve the app.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgwizard/sls/issues/115#issuecomment-288229756>, or mute
the thread

**Comment by Williwood** [comment]
Any news? They did a lot for the Bandcamp app in the past, maybe they forgot this perfect app here? And maybe they got you wrong. It is for me as if they think you are Last.fm and not an scrobble app at all.

**Comment by Benji222** [comment]
Would be great to get this going! I may try to look into it myself if I get the time!
