### ISSUE TITLE
MortPlayer Music not detected

### ISSUE THREAD

**Issue by marianoju** [tgwizard/sls#168]
Installed Simple Last.fm Scrobbler v1.4.8 from Google Play Store. No music apps detected. I am using MortPlayer Music v1.2.5.

**Comment by HumbleBeeBumbleBee** [comment]
Hi, @marianoju I am trying to solve all issues on SLS and get support for all App requests. The administrator @tgwizard hasn't been around for a while, but I will slowly be making pull requests as I develop Receivers for SLS. 
Hopefully @tgwizard comes back soon as I will have a collection for him to quickly deal with issues and merges. Example collection :)
```
APPS
#176
#175
#174 #97 #2 
#172 #126 VLC
#168 
#160
#53 pull #124

BUGS
#170
#169

Maybe Closable
#12
#34

Closable
#3
#6
#64
#111
#171
#178
``` 

Otherwise, in a about 6 months or so I am going to talk to contributors about forking it.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @marianoju [MortPlayer](https://play.google.com/store/apps/details?id=de.stohelit.folderplayer)
supports scrobbling
Quote from Google Play
>- Supports ScrobbleDroid and Simple last.fm Scrobbler (both interfaces also supported by many other scrobblers, like the official last.fm app)
It seems that MortPlayer reports as "Android Music Player" or "Scrobble Droid Apps"

**Comment by HumbleBeeBumbleBee** [comment]
If you'd like to see applications differentiated in the Enabled Apps section please see #200
