### ISSUE TITLE
"When you press the Scrobble now button" option doesn't work

### ISSUE THREAD

**Issue by moshpirit** [tgwizard/sls#173]
If I select this configuration and I listen to some band, this band it's scrobbled even if I don't press "Scrobble now".
"Now playing" works perfectly. 

V.1.4.8 (I've been using it for a long time but I noticed it now)

**Comment by HumbleBeeBumbleBee** [comment]
You mean automatic scrobbling? I think this is supposed to happen. Do you want control over scrobbling? If so, you must go to Options and select Options>Custom and When to Scrobble to When I press the Scrobble Now button.

**Comment by HumbleBeeBumbleBee** [comment]
I can't confirm this. I have been testing it for a little while now, but as long as I set "When you press the Scrobble now button" in Options, I must press "Scrobble Now" for the cached songs to be scrobbled.

Did you make sure "plugged in" and "on battery" were the same?

Otherwise,could you please give a little more information about: SLS (& version), media player (& version), android phone (& version)?

**Comment by moshpirit** [comment]
OK, I'll test it this week. And I think I'll edit the description, I don't know why I didn't write anything else :\

**Comment by HumbleBeeBumbleBee** [comment]
Merging #248
