### ISSUE TITLE
Listens successfully scrobbled to ListenBrainz remain in cache

### ISSUE THREAD

**Issue by paramsingh** [tgwizard/sls#385]
I think this is because sls expects a response beginning with `success` [here](https://github.com/tgwizard/sls/blob/d7ab95f7bbaa6f654ab5c7147c3198e13feaed8f/app/src/main/java/com/adam/aslfms/service/Scrobbler.java#L312) but the LB api has changed to returning json with our new Beta release. (https://github.com/metabrainz/listenbrainz-server/blob/master/listenbrainz/webserver/views/api.py#L75)

**Comment by EvilAaron** [comment]
Seeing submission problems and listens staying in cache since transition to beta. Reset token at listen brains and clear re entered info for SLS few time no fix. Says I'm signed in but nothing submitted all cached. Occasionally says bad username / token but clearing and entering not solving that. Info all correct according to listen brainz site.

**Comment by DerpDicler** [comment]
Yes, having the same issue as EvilAaron. Grabbed new token and seemingly logged in correctly but nothing is actually scrobbling on ListenBrainz. Last.fm and Libre.fm are working fine but the cache isn't emptying seemingly because of the LB issue.

**Comment by HumbleBeeBumbleBee** [comment]
I will fix this as soon as I can.  Thank you.

**Comment by 19379** [comment]
Ah I didn't see the above comment before submitting my PR...
