### ISSUE TITLE
Scrobbling nly happens randomly from my phone

### ISSUE THREAD

**Issue by pspringett** [tgwizard/sls#424]
Huawei P10, running Android 7.  Using  Google Play Music 8.6.6626-1.Z.  Simple last.fm 1.5.7.

Played a whole album as I was driving, only managed to get one track scrobbled.  It's been hit and miss for a few weeks now.

I did have it configured to scrobble on any network, and to submit data when roaming.  I've switched those off now and will experiment when I get a chance.  Could those settings ave been problematic?

**Comment by a93-39a** [comment]
I really just need to know if your Options or Settings are right.

Please let me know the settings or use the following Format.

##### Preferred Issue Format

  * Phone Model: (Samsung S10)
  * Android Version: (9)
  * SLS Version: (5.3)
  * Music App(s) In Use: (ex. YT Music, Spotify)
  * Detected Music Apps(s): (List what apps SLS detected)
  * Enabled Options: (List what options you have enabled)
  * Issue: (Description of What The Issue Is)
  * Parameters: (ex. When, Where, Why & How The Issue Occurs)

**Comment by pspringett** [comment]
hi, this is working now.  I suspect that an upgrade to google play music caused the problem, and then another one resolved it, but I can't be sure of course.

Thanks for following up though.

**Comment by a93-39a** [comment]
Ok. Sounds good. Thanks for the information.
