### ISSUE TITLE
Not scrobbling on LG Swift L7 (P700)

### ISSUE THREAD

**Issue by koomahnah** [tgwizard/sls#72]
To reproduce the problem, use SLS with embedded music player on LG Swift L7. Neither it doesn't work with MIUI nor Vanilla music players. In case of using Vanilla it shows "Scrobble Droid Apps" in Enabled Apps section, although it doesn't scrobble. When using embedded or MIUI, it isn't detected at all.

Please ask if you have questions, I can provide logs or something if you want. Hope you'll help. Thanks for your work! Greets (:

**Comment by HumbleBeeBumbleBee** [comment]
@koomahnah Vanilla should work.
As for MIUI I will try to find a clean .apk and test from that.

**Comment by HumbleBeeBumbleBee** [comment]
@koomahnah @iparr
I can modify the following file if you could provide debugging information.
https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/receiver/MIUIMusicReceiver.java
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by iparr** [comment]
I'm sorry, thank you for the help but my MIUI device has long since gone to the big phone shop in the sky.

**Comment by HumbleBeeBumbleBee** [comment]
@koomahnah 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by jtst** [comment]
Scrobbling from Vanilla Music also didn't work for me in my Xiaomi. Installing the above beta version by @HumbleBeeBumbleBee makes it work again.

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/tag/v1.4.9
It will include fully working Spotify support on 8/11/2015.

**Comment by HumbleBeeBumbleBee** [comment]
If anybody has anymore issues please write them here. I will close this issue for now.
