### ISSUE TITLE
Add support Sony Walkman App

### ISSUE THREAD

**Issue by loretoparisi** [tgwizard/sls#98]
Please add Add support Sony Walkman (sony media player) app

**Comment by HumbleBeeBumbleBee** [comment]
Hi everybody! Can this be closed?

**Comment by nuno-silva** [comment]
@HumbleBeeBumbleBee I've been using the official LastFm Scrobbler with the "Last.FM Scrobbler for Xperia" (suggested by @luisbandalap) because I had this issue back on November. However, I've just installed the current SLS version from Google Play on my Sony Ericsson Live Walkman (WT19i) and it seems to be working with the Walkman app on its own with the "Last.FM Scrobbler for Xperia" disabled.

**Comment by HumbleBeeBumbleBee** [comment]
This issue is closed. @loretoparisi if you disagree, please explain and I will reopening this issue.
